// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hbwsojnifesjkdwyeeqd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhid3Nvam5pZmVzamtkd3llZXFkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4Mjg2NTcsImV4cCI6MjA2OTQwNDY1N30.L6hdZa5XT9UGp0ER7cY14ddNhI8d7YPp6oEKkg9LEQI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});